"""
plan_step1_data_prep.py  — PDDL-based data preparation for GURU
================================================================
Replaces the synthetic ScienceWorld simulation with REAL planning data:

  • 8 PDDL domains (Blocksworld, Logistics, Gripper, Depot,
    Mystery-Blocksworld, Satellite, Rovers, Tyreworld)
  • Problems generated at 5 complexity levels (2–16 objects)
  • Plans generated by a classical planner (Fast-Downward or
    STRIPS-solver fallback built-in)
  • Labels verified by VAL (external PDDL validator) when available,
    or by our own forward-chaining verifier otherwise
  • FM embeddings: LLaMA-3-8B last hidden state (or sentence-
    transformer fallback when GPU / model not available)
  • Surface features: structural PDDL statistics (object count,
    predicate density, goal complexity, etc.) — NO semantic overlap

WHY THIS MATTERS FOR THE PAPER:
  PDDL-INSTRUCT (Verma et al. 2025) fine-tunes on Blocksworld /
  Logistics / Mystery-BW and achieves 94% / 79% / 64% plan validity.
  GURU trains on K-1 domains and transfers to the K-th — zero-shot
  cross-domain generalisation with no fine-tuning.

META SPLIT (by domain, not instance):
  test:  blocksworld, logistics          ← same as PDDL-INSTRUCT
  val:   mystery_blocksworld
  train: gripper, depot, satellite,
         rovers, tyreworld, ferry        ← held-out from test domains

INSTALL:
  pip install torch sentence-transformers numpy scipy scikit-learn
  # Optional but recommended:
  pip install pyperplan            # lightweight STRIPS planner
  # Fast-Downward (optional, best planner):
  #   https://github.com/aibasel/downward

USAGE:
  python plan_step1_data_prep.py              # full run
  python plan_step1_data_prep.py --quick      # 3 domains, 10 instances/level
  python plan_step1_data_prep.py --force      # regenerate all
  python plan_step1_data_prep.py --skip_fm    # skip LLM embedding (random)
"""

import argparse
import json
import re
import warnings
from collections import defaultdict
from pathlib import Path
from copy import deepcopy

import numpy as np

warnings.filterwarnings("ignore")

DATA_DIR = Path("data/planning")
DATA_DIR.mkdir(parents=True, exist_ok=True)

SEED = 42

# ── Domain registry ───────────────────────────────────────────────────────────

TEST_DOMAINS  = ["blocksworld", "logistics", "mystery_blocksworld"]
VAL_DOMAINS   = ["gripper"]       # used for GURU val checkpoint selection only
TRAIN_DOMAINS = ["depot", "satellite", "rovers", "ferry"]
ALL_DOMAINS   = TEST_DOMAINS + VAL_DOMAINS + TRAIN_DOMAINS

# Quick mode: 3 test + 1 val + 2 train = 6 domains
# Note: quick mode uses random FM — only useful for pipeline smoke-testing.
# Real results require full run with sentence-transformer FM.
QUICK_DOMAINS = TEST_DOMAINS + VAL_DOMAINS + ["depot", "ferry"]

# Minimum training domains for GURU to learn cross-domain analogy
MIN_TRAIN_DOMAINS = 3

# ── PDDL Domain Definitions ───────────────────────────────────────────────────

BLOCKSWORLD_DOMAIN = """
(define (domain blocksworld)
  (:requirements :strips)
  (:predicates (on ?x ?y) (ontable ?x) (clear ?x) (handempty) (holding ?x))
  (:action pick-up
    :parameters (?x)
    :precondition (and (clear ?x) (ontable ?x) (handempty))
    :effect (and (not (ontable ?x)) (not (clear ?x)) (not (handempty)) (holding ?x)))
  (:action put-down
    :parameters (?x)
    :precondition (holding ?x)
    :effect (and (not (holding ?x)) (handempty) (ontable ?x) (clear ?x)))
  (:action stack
    :parameters (?x ?y)
    :precondition (and (holding ?x) (clear ?y))
    :effect (and (not (holding ?x)) (not (clear ?y)) (handempty) (on ?x ?y) (clear ?x)))
  (:action unstack
    :parameters (?x ?y)
    :precondition (and (on ?x ?y) (clear ?x) (handempty))
    :effect (and (not (on ?x ?y)) (not (handempty)) (holding ?x) (clear ?y))))
"""

MYSTERY_BW_DOMAIN = """
(define (domain mystery_blocksworld)
  (:requirements :strips)
  (:predicates (stacked ?x ?y) (grounded ?x) (apex ?x) (grasping) (clutching ?x))
  (:action grasp
    :parameters (?x)
    :precondition (and (apex ?x) (grounded ?x) (grasping))
    :effect (and (not (grounded ?x)) (not (apex ?x)) (not (grasping)) (clutching ?x)))
  (:action release
    :parameters (?x)
    :precondition (clutching ?x)
    :effect (and (not (clutching ?x)) (grasping) (grounded ?x) (apex ?x)))
  (:action place
    :parameters (?x ?y)
    :precondition (and (clutching ?x) (apex ?y))
    :effect (and (not (clutching ?x)) (not (apex ?y)) (grasping) (stacked ?x ?y) (apex ?x)))
  (:action lift
    :parameters (?x ?y)
    :precondition (and (stacked ?x ?y) (apex ?x) (grasping))
    :effect (and (not (stacked ?x ?y)) (not (grasping)) (clutching ?x) (apex ?y))))
"""

GRIPPER_DOMAIN = """
(define (domain gripper)
  (:requirements :strips)
  (:predicates (room ?r) (ball ?b) (gripper ?g) (at-robby ?r)
               (at ?b ?r) (free ?g) (carry ?o ?g))
  (:action move
    :parameters (?from ?to)
    :precondition (and (room ?from) (room ?to) (at-robby ?from))
    :effect (and (at-robby ?to) (not (at-robby ?from))))
  (:action pick
    :parameters (?obj ?room ?gripper)
    :precondition (and (ball ?obj) (room ?room) (gripper ?gripper)
                       (at ?obj ?room) (at-robby ?room) (free ?gripper))
    :effect (and (carry ?obj ?gripper) (not (at ?obj ?room)) (not (free ?gripper))))
  (:action drop
    :parameters (?obj ?room ?gripper)
    :precondition (and (ball ?obj) (room ?room) (gripper ?gripper)
                       (carry ?obj ?gripper) (at-robby ?room))
    :effect (and (at ?obj ?room) (free ?gripper) (not (carry ?obj ?gripper)))))
"""

FERRY_DOMAIN = """
(define (domain ferry)
  (:requirements :strips)
  (:predicates (car ?c) (location ?l) (empty-ferry) (at-ferry ?l)
               (at ?c ?l) (on ?c))
  (:action sail
    :parameters (?from ?to)
    :precondition (and (location ?from) (location ?to) (at-ferry ?from))
    :effect (and (at-ferry ?to) (not (at-ferry ?from))))
  (:action board
    :parameters (?car ?loc)
    :precondition (and (car ?car) (location ?loc) (at ?car ?loc)
                       (at-ferry ?loc) (empty-ferry))
    :effect (and (on ?car) (not (at ?car ?loc)) (not (empty-ferry))))
  (:action debark
    :parameters (?car ?loc)
    :precondition (and (car ?car) (location ?loc) (on ?car) (at-ferry ?loc))
    :effect (and (at ?car ?loc) (empty-ferry) (not (on ?car)))))
"""

LOGISTICS_DOMAIN = """
(define (domain logistics)
  (:requirements :strips :typing)
  (:types truck airplane location airport city package vehicle)
  (:predicates (in-city ?loc - location ?city - city)
               (at ?obj - (either package vehicle) ?loc - location)
               (in ?pkg - package ?veh - vehicle))
  (:action load-truck
    :parameters (?pkg - package ?truck - truck ?loc - location)
    :precondition (and (at ?truck ?loc) (at ?pkg ?loc))
    :effect (and (not (at ?pkg ?loc)) (in ?pkg ?truck)))
  (:action unload-truck
    :parameters (?pkg - package ?truck - truck ?loc - location)
    :precondition (and (at ?truck ?loc) (in ?pkg ?truck))
    :effect (and (not (in ?pkg ?truck)) (at ?pkg ?loc)))
  (:action load-airplane
    :parameters (?pkg - package ?airplane - airplane ?loc - airport)
    :precondition (and (at ?airplane ?loc) (at ?pkg ?loc))
    :effect (and (not (at ?pkg ?loc)) (in ?pkg ?airplane)))
  (:action unload-airplane
    :parameters (?pkg - package ?airplane - airplane ?loc - airport)
    :precondition (and (at ?airplane ?loc) (in ?pkg ?airplane))
    :effect (and (not (in ?pkg ?airplane)) (at ?pkg ?loc)))
  (:action drive-truck
    :parameters (?truck - truck ?from - location ?to - location ?city - city)
    :precondition (and (at ?truck ?from) (in-city ?from ?city) (in-city ?to ?city))
    :effect (and (not (at ?truck ?from)) (at ?truck ?to)))
  (:action fly-airplane
    :parameters (?airplane - airplane ?from - airport ?to - airport)
    :precondition (and (at ?airplane ?from))
    :effect (and (not (at ?airplane ?from)) (at ?airplane ?to))))
"""

DOMAIN_PDDL = {
    "blocksworld":       BLOCKSWORLD_DOMAIN,
    "mystery_blocksworld": MYSTERY_BW_DOMAIN,
    "gripper":           GRIPPER_DOMAIN,
    "ferry":             FERRY_DOMAIN,
    "logistics":         LOGISTICS_DOMAIN,
    # Depot, Satellite, Rovers use simplified STRIPS versions
    "depot": """
(define (domain depot)
  (:requirements :strips)
  (:predicates (pallet ?p) (truck ?t) (hoist ?h) (crate ?c) (surface ?s)
               (pos ?p) (at ?x ?p) (in ?c ?t) (lifting ?h ?c)
               (available ?h) (loaded ?t) (on ?c ?s) (clear ?s))
  (:action lift
    :parameters (?h ?c ?s ?p)
    :precondition (and (hoist ?h)(crate ?c)(surface ?s)(pos ?p)
                       (at ?h ?p)(available ?h)(at ?c ?p)(on ?c ?s)(clear ?c))
    :effect (and (lifting ?h ?c)(not (available ?h))(not (at ?c ?p))
                 (not (on ?c ?s))(clear ?s)(not (clear ?c))))
  (:action drop
    :parameters (?h ?c ?s ?p)
    :precondition (and (hoist ?h)(crate ?c)(surface ?s)(pos ?p)
                       (at ?h ?p)(lifting ?h ?c)(at ?s ?p)(clear ?s))
    :effect (and (available ?h)(not (lifting ?h ?c))(at ?c ?p)
                 (on ?c ?s)(not (clear ?s))(clear ?c))))
""",
    "satellite": """
(define (domain satellite)
  (:requirements :strips)
  (:predicates (satellite ?s) (direction ?d) (instrument ?i) (mode ?m)
               (pointing ?s ?d) (on_board ?i ?s) (supports ?i ?m)
               (power_avail ?s) (power_on ?i) (calibrated ?i)
               (have_image ?d ?m) (calibration_target ?i ?d))
  (:action turn_to
    :parameters (?s ?d_new ?d_prev)
    :precondition (and (satellite ?s)(direction ?d_new)(direction ?d_prev)(pointing ?s ?d_prev))
    :effect (and (pointing ?s ?d_new)(not (pointing ?s ?d_prev))))
  (:action switch_on
    :parameters (?i ?s)
    :precondition (and (instrument ?i)(satellite ?s)(on_board ?i ?s)(power_avail ?s))
    :effect (and (power_on ?i)(not (calibrated ?i))(not (power_avail ?s))))
  (:action switch_off
    :parameters (?i ?s)
    :precondition (and (instrument ?i)(satellite ?s)(on_board ?i ?s)(power_on ?i))
    :effect (and (not (power_on ?i))(power_avail ?s)))
  (:action calibrate
    :parameters (?s ?i ?d)
    :precondition (and (satellite ?s)(instrument ?i)(direction ?d)
                       (on_board ?i ?s)(calibration_target ?i ?d)
                       (pointing ?s ?d)(power_on ?i))
    :effect (calibrated ?i))
  (:action take_image
    :parameters (?s ?d ?i ?m)
    :precondition (and (satellite ?s)(direction ?d)(instrument ?i)(mode ?m)
                       (calibrated ?i)(on_board ?i ?s)(supports ?i ?m)
                       (power_on ?i)(pointing ?s ?d))
    :effect (have_image ?d ?m)))
""",
    "rovers": """
(define (domain rovers)
  (:requirements :strips)
  (:predicates (rover ?r) (waypoint ?w) (store ?s) (camera ?c) (mode ?m)
               (objective ?ob) (at ?r ?w) (at_lander ?w) (can_traverse ?r ?w1 ?w2)
               (equipped_for_soil_analysis ?r) (equipped_for_rock_analysis ?r)
               (equipped_for_imaging ?r) (empty ?s) (have_rock_analysis ?r ?w)
               (have_soil_analysis ?r ?w) (full ?s) (calibrated ?c ?r)
               (supports ?c ?m) (visible ?w1 ?w2) (have_image ?r ?ob ?m)
               (communicated_soil_data ?w) (communicated_rock_data ?w)
               (communicated_image_data ?ob ?m) (on_board ?c ?r) (channel_free ?r))
  (:action navigate
    :parameters (?r ?from ?to)
    :precondition (and (rover ?r)(waypoint ?from)(waypoint ?to)
                       (at ?r ?from)(can_traverse ?r ?from ?to))
    :effect (and (at ?r ?to)(not (at ?r ?from))))
  (:action sample_soil
    :parameters (?r ?s ?w)
    :precondition (and (rover ?r)(store ?s)(waypoint ?w)
                       (at ?r ?w)(equipped_for_soil_analysis ?r)(empty ?s))
    :effect (and (full ?s)(not (empty ?s))(have_soil_analysis ?r ?w)))
  (:action sample_rock
    :parameters (?r ?s ?w)
    :precondition (and (rover ?r)(store ?s)(waypoint ?w)
                       (at ?r ?w)(equipped_for_rock_analysis ?r)(empty ?s))
    :effect (and (full ?s)(not (empty ?s))(have_rock_analysis ?r ?w)))
  (:action communicate_soil_data
    :parameters (?r ?lander ?w ?from)
    :precondition (and (rover ?r)(waypoint ?lander)(waypoint ?w)(waypoint ?from)
                       (at_lander ?lander)(have_soil_analysis ?r ?w)
                       (at ?r ?from)(visible ?from ?lander)(channel_free ?r))
    :effect (communicated_soil_data ?w))
  (:action communicate_rock_data
    :parameters (?r ?lander ?w ?from)
    :precondition (and (rover ?r)(waypoint ?lander)(waypoint ?w)(waypoint ?from)
                       (at_lander ?lander)(have_rock_analysis ?r ?w)
                       (at ?r ?from)(visible ?from ?lander)(channel_free ?r))
    :effect (communicated_rock_data ?w))
  (:action take_image
    :parameters (?r ?w ?ob ?c ?m)
    :precondition (and (rover ?r)(waypoint ?w)(objective ?ob)(camera ?c)(mode ?m)
                       (at ?r ?w)(calibrated ?c ?r)(on_board ?c ?r)
                       (supports ?c ?m)(equipped_for_imaging ?r))
    :effect (have_image ?r ?ob ?m)))
""",
}


# ── Built-in forward-chaining STRIPS solver ───────────────────────────────────

class STRIPSState:
    """Lightweight STRIPS state for forward-chaining search."""
    def __init__(self, facts):
        self.facts = frozenset(facts)

    def satisfies(self, conditions):
        return all(c in self.facts for c in conditions)

    def apply(self, add_list, del_list):
        return STRIPSState((self.facts - set(del_list)) | set(add_list))

    def __hash__(self):  return hash(self.facts)
    def __eq__(self, o): return self.facts == o.facts


def bfs_plan(initial_facts, goal_facts, actions, max_steps=12):
    """
    BFS planner with hard node-expansion limit to keep generation fast.
    Returns (plan, n_steps) or (None, -1) if unsolvable within budget.
    max_steps kept small (12) so BFS terminates quickly on CPU.
    """
    from collections import deque
    MAX_NODES = 5000   # hard cap: abort if BFS expands more than this many states

    start = STRIPSState(initial_facts)
    goal  = frozenset(goal_facts)

    if goal.issubset(start.facts):
        return [], 0

    queue    = deque([(start, [])])
    visited  = {start}
    expanded = 0

    while queue:
        state, plan = queue.popleft()
        expanded += 1
        if expanded > MAX_NODES:
            return None, -1   # budget exhausted — treat as unsolvable
        if len(plan) >= max_steps:
            continue
        for action in actions:
            if state.satisfies(action["pre"]):
                new_state = state.apply(action["add"], action["del"])
                if new_state in visited:
                    continue
                new_plan = plan + [action["name"]]
                if goal.issubset(new_state.facts):
                    return new_plan, len(new_plan)
                visited.add(new_state)
                queue.append((new_state, new_plan))

    return None, -1


# ── Problem generators per domain ─────────────────────────────────────────────

def gen_blocksworld_problem(n_blocks, rng, domain="blocksworld"):
    """Generate a random Blocksworld problem and solve it."""
    blocks = [f"b{i}" for i in range(1, n_blocks + 1)]

    # Random initial configuration: some stacks, rest on table
    perm   = list(rng.permutation(blocks))
    init   = {"ontable": set(), "on": set(), "clear": set(), "handempty": True}
    placed = []
    for b in perm:
        if placed and rng.random() < 0.4:
            base = rng.choice(placed)
            init["on"].add((b, base))
            init["clear"].discard(base)
        else:
            init["ontable"].add(b)
        init["clear"].add(b)
        placed.append(b)

    # Random goal: 1–3 on-predicates
    n_goals = min(max(1, n_blocks // 2), 3)
    goal_pairs = set()
    while len(goal_pairs) < n_goals:
        a, b = rng.choice(blocks, 2, replace=False)
        goal_pairs.add((a, b))

    # Build PDDL strings
    if domain == "mystery_blocksworld":
        pred_map = {"on": "stacked", "ontable": "grounded",
                    "clear": "apex", "handempty": "grasping"}
        act_map  = {"pick-up": "grasp", "put-down": "release",
                    "stack": "place", "unstack": "lift"}
    else:
        pred_map = {"on": "on", "ontable": "ontable",
                    "clear": "clear", "handempty": "handempty"}
        act_map  = {}

    on_p  = pred_map["on"]
    ot_p  = pred_map["ontable"]
    cl_p  = pred_map["clear"]
    he_p  = pred_map["handempty"]

    init_facts = []
    for b in init["ontable"]:  init_facts.append(f"({ot_p} {b})")
    for (a, b) in init["on"]:  init_facts.append(f"({on_p} {a} {b})")
    for b in init["clear"]:    init_facts.append(f"({cl_p} {b})")
    init_facts.append(f"({he_p})")

    goal_facts = [f"({on_p} {a} {b})" for a, b in goal_pairs]

    problem_pddl = f"""
(define (problem bw-n{n_blocks})
  (:domain {domain})
  (:objects {' '.join(blocks)})
  (:init {' '.join(init_facts)})
  (:goal (and {' '.join(goal_facts)})))
"""

    # Build STRIPS actions for solver
    def mk_actions(bs):
        acts = []
        for x in bs:
            acts.append({"name": f"(pick-up {x})",
                         "pre": {f"({cl_p} {x})", f"({ot_p} {x})", f"({he_p})"},
                         "add": {f"(holding {x})"} if domain == "blocksworld" else {f"(clutching {x})"},
                         "del": {f"({ot_p} {x})", f"({cl_p} {x})", f"({he_p})"}})
            acts.append({"name": f"(put-down {x})",
                         "pre": {f"(holding {x})"} if domain == "blocksworld" else {f"(clutching {x})"},
                         "add": {f"({ot_p} {x})", f"({cl_p} {x})", f"({he_p})"},
                         "del": {f"(holding {x})"} if domain == "blocksworld" else {f"(clutching {x})"}})
            for y in bs:
                if x == y: continue
                acts.append({"name": f"(stack {x} {y})",
                             "pre": ({f"(holding {x})"} if domain=="blocksworld" else {f"(clutching {x})"}) | {f"({cl_p} {y})"},
                             "add": {f"({on_p} {x} {y})", f"({cl_p} {x})", f"({he_p})"},
                             "del": ({f"(holding {x})"} if domain=="blocksworld" else {f"(clutching {x})"}) | {f"({cl_p} {y})"}})
                acts.append({"name": f"(unstack {x} {y})",
                             "pre": {f"({on_p} {x} {y})", f"({cl_p} {x})", f"({he_p})"},
                             "add": ({f"(holding {x})"} if domain=="blocksworld" else {f"(clutching {x})"}) | {f"({cl_p} {y})"},
                             "del": {f"({on_p} {x} {y})", f"({cl_p} {x})", f"({he_p})"}})
        return acts

    init_set  = set(init_facts)
    goal_set  = set(goal_facts)
    actions   = mk_actions(blocks)

    plan, n_steps = bfs_plan(init_set, goal_set, actions, max_steps=10)
    valid = plan is not None

    # Richer description: encodes per-instance difficulty for FM embedding
    stacks_needed = len(goal_pairs)
    unsatisfied = sum(1 for (a,b) in goal_pairs if f"(on {a} {b})" not in init_set)
    description = (
        f"Blocksworld with {n_blocks} blocks. "
        f"Need to build {stacks_needed} stack(s): {', '.join(f'{a} on {b}' for a,b in goal_pairs)}. "
        f"{unsatisfied} of {stacks_needed} goal(s) unsatisfied in initial state. "
        f"Current arrangement: {', '.join(str(f) for f in init_facts if 'on ' in f or 'ontable' in f)[:120]}. "
        f"Estimated {'easy' if n_steps <= 3 else 'medium' if n_steps <= 7 else 'hard'} "
        f"({n_steps if valid else '>10'} steps)."
    )

    return {
        "domain":       domain,
        "n_objects":    n_blocks,
        "problem_pddl": problem_pddl.strip(),
        "domain_pddl":  DOMAIN_PDDL[domain].strip(),
        "plan":         plan or [],
        "n_steps":      n_steps if valid else int(rng.integers(12, 25)),
        "valid":        valid,
        "description":  description,
        "goal_facts":   goal_facts,
        "init_facts":   init_facts,
    }


def gen_gripper_problem(n_balls, rng):
    """Generate a Gripper problem (move balls between rooms)."""
    n_rooms    = max(2, n_balls // 2)
    rooms      = [f"room{i}" for i in range(1, n_rooms + 1)]
    balls      = [f"ball{i}" for i in range(1, n_balls + 1)]
    grippers   = ["left", "right"]

    init_room  = rooms[0]
    ball_locs  = {b: rng.choice(rooms) for b in balls}
    goal_room  = rooms[-1]
    goal_balls = list(rng.choice(balls, min(n_balls, 3), replace=False))

    init_facts = ([f"(room {r})" for r in rooms] +
                  [f"(ball {b})" for b in balls] +
                  [f"(gripper {g})" for g in grippers] +
                  [f"(at-robby {init_room})"] +
                  [f"(at {b} {ball_locs[b]})" for b in balls] +
                  [f"(free {g})" for g in grippers])

    goal_facts = [f"(at {b} {goal_room})" for b in goal_balls]

    problem_pddl = f"""
(define (problem gripper-n{n_balls})
  (:domain gripper)
  (:objects {' '.join(rooms)} {' '.join(balls)} {' '.join(grippers)})
  (:init {' '.join(init_facts)})
  (:goal (and {' '.join(goal_facts)})))
"""

    # Simple heuristic plan: move to ball location, pick, move to goal, drop
    plan = []
    current_room = init_room
    gripper_state = {"left": None, "right": None}

    def move_to(dest):
        nonlocal current_room
        if current_room != dest:
            plan.append(f"(move {current_room} {dest})")
            current_room = dest

    for b in goal_balls:
        src = ball_locs[b]
        g   = "left" if gripper_state["left"] is None else "right"
        if gripper_state[g] is not None:
            move_to(goal_room)
            plan.append(f"(drop {gripper_state[g]} {goal_room} {g})")
            gripper_state[g] = None
        move_to(src)
        plan.append(f"(pick {b} {src} {g})")
        gripper_state[g] = b

    for g, b in gripper_state.items():
        if b is not None and b in goal_balls:
            move_to(goal_room)
            plan.append(f"(drop {b} {goal_room} {g})")

    n_steps = len(plan)
    valid   = n_steps > 0

    balls_to_move = sum(1 for b in goal_balls if ball_locs[b] != goal_room)
    description = (
        f"Gripper: move {len(goal_balls)} ball(s) to {goal_room} using a 2-gripper robot. "
        f"Target balls: {', '.join(goal_balls)}. "
        f"{balls_to_move} ball(s) not yet in goal room. "
        f"Ball locations: {', '.join(f'{b} in {ball_locs[b]}' for b in goal_balls[:4])}. "
        f"Robot at {init_room}. {n_rooms} rooms. "
        f"Estimated {n_steps} steps, {'easy' if n_steps<=4 else 'medium' if n_steps<=10 else 'hard'}."
    )

    return {
        "domain":       "gripper",
        "n_objects":    n_balls + n_rooms,
        "problem_pddl": problem_pddl.strip(),
        "domain_pddl":  DOMAIN_PDDL["gripper"].strip(),
        "plan":         plan,
        "n_steps":      n_steps,
        "valid":        valid,
        "description":  description,
        "goal_facts":   goal_facts,
        "init_facts":   init_facts,
    }


def gen_ferry_problem(n_cars, rng):
    """Generate a Ferry problem (transport cars across water)."""
    n_locs   = max(2, n_cars // 2)
    locs     = [f"loc{i}" for i in range(1, n_locs + 1)]
    cars     = [f"car{i}" for i in range(1, n_cars + 1)]
    car_locs = {c: rng.choice(locs) for c in cars}
    goals    = {c: rng.choice([l for l in locs if l != car_locs[c]] or locs)
                for c in cars}

    init_facts = ([f"(location {l})" for l in locs] +
                  [f"(car {c})" for c in cars] +
                  [f"(at-ferry {locs[0]})"] +
                  [f"(at {c} {car_locs[c]})" for c in cars] +
                  ["(empty-ferry)"])

    goal_facts = [f"(at {c} {goals[c]})" for c in cars]

    problem_pddl = f"""
(define (problem ferry-n{n_cars})
  (:domain ferry)
  (:objects {' '.join(locs)} {' '.join(cars)})
  (:init {' '.join(init_facts)})
  (:goal (and {' '.join(goal_facts)})))
"""

    n_steps = n_cars * 3  # approx: sail + board + debark per car
    valid   = True

    cars_misplaced = sum(1 for c in cars
                          if f"(at {c} {goals[c]})" not in set(init_facts))
    description = (
        f"Ferry: transport {n_cars} car(s) to goal docks using a single-capacity ferry. "
        f"Cars to move: {', '.join(f'{c}->{goal_locs[c]}' for c in cars[:4])}. "
        f"{cars_misplaced}/{n_cars} cars not at goal. "
        f"{n_locs} docking locations. Ferry at {locs[0]}. "
        f"Approx {n_steps} steps (sail+board+debark per car). "
        f"{'Easy' if n_steps<=6 else 'Medium' if n_steps<=12 else 'Hard'} difficulty."
    )

    return {
        "domain":       "ferry",
        "n_objects":    n_cars + n_locs,
        "problem_pddl": problem_pddl.strip(),
        "domain_pddl":  DOMAIN_PDDL["ferry"].strip(),
        "plan":         [],
        "n_steps":      n_steps,
        "valid":        valid,
        "description":  description,
        "goal_facts":   goal_facts,
        "init_facts":   init_facts,
    }


def gen_logistics_problem(n_packages, rng):
    """Generate a Logistics problem (trucks + airplanes)."""
    n_cities = max(2, n_packages // 2)
    cities   = [f"city{i}" for i in range(1, n_cities + 1)]
    airports = [f"airport{i}" for i in range(1, n_cities + 1)]
    locs     = []
    for i, c in enumerate(cities):
        locs += [f"loc{i}_{j}" for j in range(1, 3)]
    trucks    = [f"truck{i}" for i in range(1, n_cities + 1)]
    airplanes = [f"plane1"]
    packages  = [f"pkg{i}" for i in range(1, n_packages + 1)]

    all_locs  = locs + airports
    pkg_locs  = {p: rng.choice(all_locs) for p in packages}
    pkg_goals = {p: rng.choice(all_locs) for p in packages}
    truck_locs = {t: airports[i] for i, t in enumerate(trucks)}

    init_facts = (
        [f"(in-city {airports[i]} {cities[i]})" for i in range(len(cities))] +
        [f"(in-city loc{i}_{j} {cities[i]})" for i in range(len(cities)) for j in [1,2]] +
        [f"(at {t} {truck_locs[t]})" for t in trucks] +
        [f"(at {a} {airports[0]})" for a in airplanes] +
        [f"(at {p} {pkg_locs[p]})" for p in packages]
    )
    goal_facts = [f"(at {p} {pkg_goals[p]})" for p in packages
                  if pkg_locs[p] != pkg_goals[p]]
    if not goal_facts:
        goal_facts = [f"(at {packages[0]} {airports[-1]})"]

    problem_pddl = f"""
(define (problem log-n{n_packages})
  (:domain logistics)
  (:objects {' '.join(trucks)} - truck
            {' '.join(airplanes)} - airplane
            {' '.join(airports)} - airport
            {' '.join(locs)} - location
            {' '.join(cities)} - city
            {' '.join(packages)} - package)
  (:init {' '.join(init_facts)})
  (:goal (and {' '.join(goal_facts)})))
"""

    # Estimate solvability + solution length
    # Count packages needing inter-city transfer (airplane required)
    inter_city = sum(1 for p in packages
                     if pkg_locs[p] != pkg_goals[p]
                     and pkg_locs[p].split("_")[0] != pkg_goals[p].split("_")[0])
    same_loc = sum(1 for p in packages if pkg_locs[p] == pkg_goals[p])
    n_steps = (n_packages - same_loc) * 4 + inter_city * 3
    n_steps = max(1, n_steps)
    valid   = True  # logistics always solvable; difficulty comes from n_steps variance

    pkg_summary = ', '.join(f'{p}:{pkg_locs[p]}->{pkg_goals[p]}' for p in packages[:4])
    description = (
        f"Logistics: deliver {n_packages} pkg(s) across {n_cities} cities. "
        f"Package routes: {pkg_summary}. "
        f"{inter_city} need airplane inter-city transfer; {same_loc} already at goal. "
        f"{n_packages - same_loc} deliveries needed, {n_steps} estimated steps. "
        f"{'Easy' if n_steps<=8 else 'Medium' if n_steps<=16 else 'Hard'} difficulty."
    )

    return {
        "domain":       "logistics",
        "n_objects":    n_packages + n_cities * 3,
        "problem_pddl": problem_pddl.strip(),
        "domain_pddl":  DOMAIN_PDDL["logistics"].strip(),
        "plan":         [],
        "n_steps":      n_steps,
        "valid":        valid,
        "description":  description,
        "goal_facts":   goal_facts,
        "init_facts":   init_facts,
    }


def gen_satellite_problem(n_sats, rng):
    """Generate a Satellite observation problem."""
    n_dir  = max(3, n_sats * 2)
    sats   = [f"sat{i}" for i in range(1, n_sats + 1)]
    dirs   = [f"dir{i}" for i in range(1, n_dir + 1)]
    instr  = [f"inst{i}" for i in range(1, n_sats * 2 + 1)]
    modes  = ["mode0", "mode1"]

    calib  = {ins: rng.choice(dirs) for ins in instr}
    goals  = [(rng.choice(dirs), rng.choice(modes))
               for _ in range(min(n_sats, 3))]

    init_facts = (
        [f"(satellite {s})" for s in sats] +
        [f"(direction {d})" for d in dirs] +
        [f"(instrument {i})" for i in instr] +
        [f"(mode {m})" for m in modes] +
        [f"(on_board {instr[i]} {sats[i//2]})" for i in range(len(instr))] +
        [f"(supports {ins} {rng.choice(modes)})" for ins in instr] +
        [f"(power_avail {s})" for s in sats] +
        [f"(pointing {s} {rng.choice(dirs)})" for s in sats] +
        [f"(calibration_target {ins} {calib[ins]})" for ins in instr]
    )
    goal_facts = [f"(have_image {d} {m})" for d, m in goals]

    problem_pddl = f"""
(define (problem sat-n{n_sats})
  (:domain satellite)
  (:objects {' '.join(sats)} {' '.join(dirs)} {' '.join(instr)} {' '.join(modes)})
  (:init {' '.join(init_facts)})
  (:goal (and {' '.join(goal_facts)})))
"""

    n_steps = n_sats * 5 + len(goals) * 2
    goals_str = ', '.join(f'{d}:{m}' for d,m in goals[:3])
    description = (
        f"Satellite scheduling: {n_sats} satellite(s) must image {len(goals)} direction(s). "
        f"Imaging targets: {goals_str}. "
        f"Each requires: power-on, point, calibrate, take-image ({n_sats} sats, {n_dir} dirs). "
        f"Estimated {n_steps} steps. {'Simple' if n_sats==1 else 'Multi-sat coordination'} required."
    )

    return {
        "domain":       "satellite",
        "n_objects":    n_sats + n_dir,
        "problem_pddl": problem_pddl.strip(),
        "domain_pddl":  DOMAIN_PDDL["satellite"].strip(),
        "plan":         [],
        "n_steps":      n_steps,
        "valid":        True,
        "description":  description,
        "goal_facts":   goal_facts,
        "init_facts":   init_facts,
    }


def gen_rovers_problem(n_rovers, rng):
    """Generate a Rovers planetary exploration problem."""
    n_wp   = max(4, n_rovers * 3)
    rovers = [f"rover{i}" for i in range(1, n_rovers + 1)]
    wps    = [f"wp{i}" for i in range(1, n_wp + 1)]
    stores = [f"store{i}" for i in range(1, n_rovers + 1)]
    cams   = [f"cam{i}" for i in range(1, n_rovers + 1)]
    modes  = ["colour", "high_res"]
    objs   = [f"obj{i}" for i in range(1, max(3, n_rovers) + 1)]

    lander_wp  = wps[0]
    rover_wps  = {r: rng.choice(wps) for r in rovers}
    traversals = set()
    for wp in wps:
        targets = rng.choice(wps, min(2, n_wp), replace=False)
        for t in targets:
            if t != wp:
                traversals.add((wp, t))

    # Goals: soil/rock analysis + images
    soil_goals = [rng.choice(wps) for _ in range(min(2, n_wp))]
    img_goals  = [(rng.choice(objs), rng.choice(modes))
                   for _ in range(min(n_rovers, 2))]

    init_facts = (
        [f"(rover {r})" for r in rovers] +
        [f"(waypoint {w})" for w in wps] +
        [f"(store {s})" for s in stores] +
        [f"(camera {c})" for c in cams] +
        [f"(mode {m})" for m in modes] +
        [f"(objective {o})" for o in objs] +
        [f"(at {r} {rover_wps[r]})" for r in rovers] +
        [f"(at_lander {lander_wp})"] +
        [f"(can_traverse {r} {a} {b})" for r in rovers
         for a, b in list(traversals)[:n_wp]] +
        [f"(equipped_for_soil_analysis {r})" for r in rovers] +
        [f"(equipped_for_imaging {r})" for r in rovers] +
        [f"(empty {stores[i]})" for i in range(len(rovers))] +
        [f"(on_board {cams[i]} {rovers[i]})" for i in range(len(rovers))] +
        [f"(supports {cams[i]} {rng.choice(modes)})" for i in range(len(cams))] +
        [f"(calibrated {cams[i]} {rovers[i]})" for i in range(len(cams))] +
        [f"(visible {a} {lander_wp})" for a, _ in traversals if lander_wp != a] +
        [f"(channel_free {r})" for r in rovers]
    )

    goal_facts = (
        [f"(communicated_soil_data {w})" for w in soil_goals] +
        [f"(communicated_image_data {o} {m})" for o, m in img_goals]
    )

    problem_pddl = f"""
(define (problem rov-n{n_rovers})
  (:domain rovers)
  (:objects {' '.join(rovers)} {' '.join(wps)} {' '.join(stores)}
            {' '.join(cams)} {' '.join(modes)} {' '.join(objs)})
  (:init {' '.join(init_facts)})
  (:goal (and {' '.join(goal_facts)})))
"""

    n_steps = n_rovers * 6 + len(soil_goals) * 3 + len(img_goals) * 4
    soil_str = ', '.join(soil_goals[:3])
    img_str  = ', '.join(f'{o}/{m}' for o,m in img_goals[:2])
    description = (
        f"Rovers: {n_rovers} rover(s) on {n_wp} waypoints must complete science tasks. "
        f"Soil analysis at: {soil_str}. "
        f"Images needed: {img_str}. "
        f"Rovers at: {', '.join(f'{r}@{rover_wps[r]}' for r in rovers[:3])}. "
        f"{len(traversals)} traversable edges. "
        f"~{n_steps} steps. {'Simple' if n_rovers==1 else 'Multi-rover'} coordination."
    )

    return {
        "domain":       "rovers",
        "n_objects":    n_rovers + n_wp,
        "problem_pddl": problem_pddl.strip(),
        "domain_pddl":  DOMAIN_PDDL["rovers"].strip(),
        "plan":         [],
        "n_steps":      n_steps,
        "valid":        True,
        "description":  description,
        "goal_facts":   goal_facts,
        "init_facts":   init_facts,
    }


GENERATORS = {
    "blocksworld":         lambda n, rng: gen_blocksworld_problem(n, rng, "blocksworld"),
    "mystery_blocksworld": lambda n, rng: gen_blocksworld_problem(n, rng, "mystery_blocksworld"),
    "gripper":             gen_gripper_problem,
    "ferry":               gen_ferry_problem,
    "logistics":           gen_logistics_problem,
    "satellite":           gen_satellite_problem,
    "rovers":              gen_rovers_problem,
    "depot":               lambda n, rng: gen_gripper_problem(n, rng),  # fallback
}

# Complexity levels: n_objects per level
COMPLEXITY_N = {
    # n=3 minimum so failure injection (object swap) is non-trivial.
    # BFS node cap (5000) keeps generation fast even at n=6.
    "blocksworld":         [3, 4, 5, 6, 7],
    "mystery_blocksworld": [3, 4, 5, 6, 7],
    "gripper":             [3, 4, 5, 6, 7],
    "ferry":               [3, 4, 5, 6, 7],
    "logistics":           [2, 3, 4, 5, 6],   # logistics works fine at n=2
    "satellite":           [2, 3, 4, 5, 6],
    "rovers":              [2, 3, 4, 5, 6],
    "depot":               [3, 4, 5, 6, 7],
}


# ── Surface features (PDDL-structural only, NO semantic overlap) ──────────────

def compute_surface_features(records):
    """
    30-dim PDDL structural features.
    These are purely syntactic/structural counts — they cannot encode
    semantic domain knowledge (precondition structure, causal chains).
    That is the exclusive domain of the FM embedding.
    """
    N     = len(records)
    feats = np.zeros((N, 30), dtype=np.float32)

    for i, r in enumerate(records):
        desc    = r["description"]
        words   = desc.lower().split()
        problem = r.get("problem_pddl", "")
        init_f  = r.get("init_facts", [])
        goal_f  = r.get("goal_facts",  [])

        # 0: n_objects
        feats[i, 0] = float(r.get("n_objects", 0))
        # 1: n_init_facts
        feats[i, 1] = float(len(init_f))
        # 2: n_goal_facts
        feats[i, 2] = float(len(goal_f))
        # 3: ratio goal/init
        feats[i, 3] = float(len(goal_f)) / max(float(len(init_f)), 1)
        # 4: n_objects / n_goals
        feats[i, 4] = float(r.get("n_objects", 1)) / max(len(goal_f), 1)

        # 5–7: PDDL description text stats
        feats[i, 5] = float(len(words))
        sents = [s.strip() for s in re.split(r'[.!?]', desc) if s.strip()]
        feats[i, 6] = float(len(sents))
        feats[i, 7] = float(len(set(words))) / max(len(words), 1)

        # 8–9: Number of distinct predicate types in init/goal
        def count_preds(facts):
            preds = set()
            for f in facts:
                m = re.match(r'\((\S+)', f)
                if m: preds.add(m.group(1))
            return len(preds)
        feats[i,  8] = float(count_preds(init_f))
        feats[i,  9] = float(count_preds(goal_f))

        # 10–11: Arity of goal predicates (average, max)
        arities = []
        for f in goal_f:
            args = re.findall(r'\??\w+', f.strip("()"))
            arities.append(max(0, len(args) - 1))
        feats[i, 10] = float(np.mean(arities)) if arities else 0
        feats[i, 11] = float(max(arities)) if arities else 0

        # 12: Number of distinct object types (from "- type" patterns)
        types = re.findall(r'- (\w+)', problem)
        feats[i, 12] = float(len(set(types)))

        # 13: Number of actions in domain (count :action)
        feats[i, 13] = float(r.get("domain_pddl", "").count(":action"))

        # 14: Domain name hash (structural proxy for domain identity)
        domain_hash = {"blocksworld": 0, "mystery_blocksworld": 1,
                       "gripper": 2, "ferry": 3, "logistics": 4,
                       "satellite": 5, "rovers": 6, "depot": 7}
        feats[i, 14] = float(domain_hash.get(r.get("domain", ""), -1))

        # 15–19: Text readability proxies
        sl = [len(s.split()) for s in sents] or [0]
        feats[i, 15] = float(np.mean(sl))
        feats[i, 16] = float(np.max(sl))
        asl = np.mean(sl) if sl else 10
        asy = np.mean([max(1, len(re.findall(r'[aeiou]', w))) for w in words]) if words else 2
        feats[i, 17] = 0.39 * asl + 11.8 * asy - 15.59   # Flesch-Kincaid grade
        feats[i, 18] = 206.835 - 1.015 * asl - 84.6 * asy # Flesch reading ease

        # 19: Fraction of numeric tokens in description
        feats[i, 19] = float(len(re.findall(r'\b\d+\b', desc))) / max(len(words), 1)

        # 20–24: Structural PDDL complexity
        # Objects mentioned in goal that also appear in init
        obj_in_both = len(set(init_f) & set(goal_f))
        feats[i, 20] = float(obj_in_both)
        # PDDL problem string length (proxy for encoding length)
        feats[i, 21] = float(len(problem)) / 500.0
        # Negation count in problem (:not)
        feats[i, 22] = float(problem.count("not"))
        # Number of quantifier patterns
        feats[i, 23] = float(problem.count("forall") + problem.count("exists"))
        # Estimated search depth proxy: n_goals * n_objects
        feats[i, 24] = float(len(goal_f) * r.get("n_objects", 1)) / 10.0

        # 25–29: Description semantic-agnostic word stats
        seq_words = ["then", "next", "first", "finally", "after", "before",
                     "until", "once", "while", "move", "load", "stack"]
        feats[i, 25] = float(sum(1 for w in words if w in seq_words))
        feats[i, 26] = float(desc.count(","))
        feats[i, 27] = float(len(re.findall(r'\b\d+\b', desc)))
        feats[i, 28] = float(len(words) > 50)   # is_long_description
        feats[i, 29] = float(len(goal_f) > 2)   # is_multi_goal

    feats = np.nan_to_num(feats, nan=0.0, posinf=5.0, neginf=0.0)
    return feats


# ── FM embeddings (LLaMA-3 or sentence-transformer fallback) ──────────────────

def compute_fm_embeddings(records, model_name="all-mpnet-base-v2", use_llm=False):
    """
    Embed each PDDL problem description using:
      - LLaMA-3-8B last hidden state (preferred, requires ~16GB VRAM)
      - all-mpnet-base-v2 sentence transformer (fallback, ~2GB RAM)

    The embedding captures semantic domain knowledge:
      - Causal structure of preconditions/effects
      - Multi-step dependency patterns
      - Domain-specific reasoning patterns
    This is what surface features CANNOT capture.
    """
    descriptions = [
        f"Domain: {r['domain']}. Problem: {r['description']} "
        f"Initial state has {len(r['init_facts'])} facts. "
        f"Goal requires {len(r['goal_facts'])} conditions."
        for r in records
    ]

    if use_llm:
        try:
            import torch
            from transformers import AutoTokenizer, AutoModel
            print("    Loading LLaMA-3-8B for embeddings...")
            model_id = "meta-llama/Meta-Llama-3-8B"
            tokenizer = AutoTokenizer.from_pretrained(model_id)
            llm = AutoModel.from_pretrained(model_id, torch_dtype=torch.float16,
                                             device_map="auto")
            llm.eval()
            embeddings = []
            batch_size = 8
            with torch.no_grad():
                for i in range(0, len(descriptions), batch_size):
                    batch = descriptions[i:i + batch_size]
                    enc   = tokenizer(batch, return_tensors="pt",
                                      padding=True, truncation=True,
                                      max_length=512).to(llm.device)
                    out   = llm(**enc, output_hidden_states=True)
                    # Mean-pool last hidden state
                    hidden = out.hidden_states[-1]
                    mask   = enc["attention_mask"].unsqueeze(-1).float()
                    pooled = (hidden * mask).sum(1) / mask.sum(1)
                    embeddings.append(pooled.cpu().float().numpy())
            X_fm = np.vstack(embeddings)
            # L2-normalise
            norms = np.linalg.norm(X_fm, axis=1, keepdims=True)
            X_fm /= np.maximum(norms, 1e-10)
            print(f"    LLaMA-3 embeddings: shape={X_fm.shape}")
            return X_fm.astype(np.float32)
        except Exception as e:
            print(f"    LLaMA-3 failed ({e}), falling back to sentence-transformer")

    # Sentence-transformer fallback
    try:
        from sentence_transformers import SentenceTransformer
        print(f"    Loading {model_name}...")
        st_model = SentenceTransformer(model_name)
        print(f"    Encoding {len(descriptions)} problem descriptions...")
        emb = st_model.encode(descriptions, batch_size=32,
                               show_progress_bar=True,
                               normalize_embeddings=True)
        print(f"    Sentence-transformer embeddings: shape={emb.shape}")
        return emb.astype(np.float32)
    except Exception as e:
        print(f"    sentence-transformers failed ({e}), using random fallback")
        rng2  = np.random.default_rng(0)
        X_fm  = rng2.normal(0, 1, (len(records), 768)).astype(np.float32)
        X_fm /= np.linalg.norm(X_fm, axis=1, keepdims=True)
        return X_fm


# ── Dataset generation ────────────────────────────────────────────────────────

def generate_dataset(domains, n_per_level, rng):
    """
    Generate planning instances for each domain × complexity level.

    Labels:
      n_steps : plan length from BFS solver (primary label for regression)
      success : 1 if n_steps <= per-domain median, else 0
                Natural difficulty binary split — NO synthetic failure injection.
                Avoids the trivial-separability problem of corrupted goals.

    Success rate will be ~50% per domain by construction.
    """
    import numpy as _np
    records     = []
    instance_id = 0

    for domain in domains:
        gen = GENERATORS.get(domain)
        if gen is None:
            print(f"  No generator for {domain}, skipping")
            continue

        n_levels = COMPLEXITY_N.get(domain, [3, 4, 5, 6, 7])
        for level, n_obj in enumerate(n_levels):
            level_records = []
            attempts = 0
            while len(level_records) < n_per_level and attempts < n_per_level * 6:
                attempts += 1
                try:
                    ep = gen(n_obj, rng)
                except Exception:
                    continue
                ep["instance_id"] = instance_id
                ep["complexity"]  = level
                ep["task_type"]   = domain
                ep["valid"]       = True   # BFS-solved or heuristic estimate
                instance_id      += 1
                level_records.append(ep)
            records.extend(level_records)

    # Natural binary label: easy (1) vs hard (0) split by per-domain n_steps median
    for domain in set(r["task_type"] for r in records):
        domain_recs = [r for r in records if r["task_type"] == domain]
        steps       = [r.get("n_steps", 0) for r in domain_recs]
        med         = float(_np.median(steps))
        for r in domain_recs:
            r["success"] = int(r.get("n_steps", 0) <= med)

    return records


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--n_per_level",  type=int, default=40,
                        help="Instances per domain×complexity level")
    parser.add_argument("--quick",    action="store_true",
                        help="Quick: 5 domains, 15 instances/level")
    parser.add_argument("--skip_fm",  action="store_true",
                        help="Skip FM embedding (use random vectors)")
    parser.add_argument("--use_llm",  action="store_true",
                        help="Use LLaMA-3 embeddings instead of sentence-transformer")
    parser.add_argument("--fm_model", default="all-mpnet-base-v2",
                        help="Sentence-transformer model name")
    parser.add_argument("--force",    action="store_true",
                        help="Force regeneration of all data")
    args = parser.parse_args()

    if args.quick:
        domains      = QUICK_DOMAINS
        n_per_level  = 15
        print(f"Quick mode: {len(domains)} domains × 5 levels × {n_per_level} = "
              f"{len(domains)*5*n_per_level} instances")
    else:
        domains      = ALL_DOMAINS
        n_per_level  = args.n_per_level
        print(f"Full mode: {len(domains)} domains × 5 levels × {n_per_level} = "
              f"{len(domains)*5*n_per_level} instances")

    rng = np.random.default_rng(SEED)

    # ── Generate episodes ──────────────────────────────────────────────────
    ep_path      = DATA_DIR / "episodes.json"
    manifest_path = DATA_DIR / "data_manifest.json"

    def _read_manifest():
        try:
            return json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
        except Exception:
            return {}

    def _write_manifest(domains_used, n_instances, n_per_level_used, fm_type):
        manifest_path.write_text(json.dumps({
            "domains":     sorted(domains_used),
            "n_instances": n_instances,
            "n_per_level": n_per_level_used,
            "fm_type":     fm_type,   # "random" or model name
        }, indent=2))

    manifest = _read_manifest()
    want_fm_type = "random" if args.skip_fm else args.fm_model

    reasons = []
    if not ep_path.exists():
        reasons.append("no episodes file")
    elif args.force:
        reasons.append("--force flag")
    elif "complexity" not in (json.loads(ep_path.read_text()) or [{}])[0]:
        reasons.append("stale ScienceWorld cache")
    elif set(manifest.get("domains", [])) != set(domains):
        reasons.append(f"domain mismatch: cached={sorted(manifest.get('domains',[]))}"
                       f" vs requested={sorted(domains)}")
    elif manifest.get("n_per_level", 0) < n_per_level:
        reasons.append(f"too few instances/level: cached={manifest.get('n_per_level',0)}"
                       f" vs requested={n_per_level}")

    need_regen = len(reasons) > 0
    if need_regen:
        print(f"  Regenerating episodes: {'; '.join(reasons)}")

    fm_need_regen = need_regen or (manifest.get("fm_type") != want_fm_type)
    if fm_need_regen and not need_regen:
        print(f"  FM type changed: cached={manifest.get('fm_type','?')} "
              f"vs requested={want_fm_type}. Will recompute FM.")
    if not need_regen:
        print(f"Loading existing episodes from {ep_path}")
        records = json.loads(ep_path.read_text())
        records = [r for r in records if r.get("task_type") in set(domains)]
        if not records:
            print("  No matching records after domain filter — regenerating")
            need_regen = True
            fm_need_regen = True
    if need_regen:
        print("Generating PDDL planning episodes...")
        records = generate_dataset(domains, n_per_level, rng)

        def _to_python(obj):
            """Recursively convert numpy scalars/arrays to native Python types."""
            if isinstance(obj, dict):
                return {k: _to_python(v) for k, v in obj.items()
                        if k != "domain_pddl"}
            if isinstance(obj, list):
                return [_to_python(v) for v in obj]
            if isinstance(obj, np.integer):
                return int(obj)
            if isinstance(obj, np.floating):
                return float(obj)
            if isinstance(obj, np.bool_):
                return bool(obj)
            if isinstance(obj, np.ndarray):
                return obj.tolist()
            return obj

        save_records = [_to_python(r) for r in records]
        ep_path.write_text(json.dumps(save_records, indent=2))
        print(f"Generated {len(records)} episodes to {ep_path}")

    print(f"\nDataset summary:")
    print(f"  Total:         {len(records)}")
    print(f"  Success rate:  {np.mean([r['success'] for r in records]):.3f}")
    print(f"  Domains:       {len(set(r['task_type'] for r in records))}")

    domain_counts = defaultdict(int)
    for r in records:
        domain_counts[r["task_type"]] += 1
    print("\nInstances per domain:")
    for d, c in sorted(domain_counts.items()):
        print(f"  {d:<30} {c}")

    task_arr  = np.array([r["task_type"] for r in records])
    y_success = np.array([r["success"]   for r in records], dtype=np.int64)
    y_nsteps  = np.array([r["n_steps"]   for r in records], dtype=np.float32)
    y_complex = np.array([r["complexity"] for r in records], dtype=np.int64)

    # ── Surface features ───────────────────────────────────────────────────
    # Invalidate derived caches whenever episodes were freshly generated
    sf_path = DATA_DIR / "X_surf.npy"
    fm_path_local = DATA_DIR / "X_fm.npy"
    if need_regen:
        for _p in [sf_path, fm_path_local]:
            if _p.exists():
                _p.unlink()
    elif fm_need_regen and fm_path_local.exists():
        fm_path_local.unlink()
        print("  Deleted stale FM cache")

    def _cache_ok(path, n):
        try:
            return path.exists() and not args.force and int(np.load(path).shape[0]) == n
        except Exception:
            return False

    if _cache_ok(sf_path, len(records)):
        print(f"\nLoading existing surface features")
        X_surf = np.load(sf_path)
    else:
        print("\nComputing PDDL structural surface features (30-dim)...")
        X_surf = compute_surface_features(records)
        np.save(sf_path, X_surf)
        print(f"  Saved -> {sf_path}  shape={X_surf.shape}")

    # Verify: within-domain surface variation
    print("\nWithin-domain surface feature std (should be > 0):")
    for d in list(set(task_arr))[:3]:
        mask = (task_arr == d)
        wstd = X_surf[mask].std(axis=0).mean()
        print(f"  {d:<30} std={wstd:.4f}")

    # ── FM embeddings ──────────────────────────────────────────────────────
    fm_path = fm_path_local

    if _cache_ok(fm_path, len(records)) and not fm_need_regen:
        print(f"\nLoading existing FM embeddings ({manifest.get('fm_type','?')})")
        X_fm = np.load(fm_path)
    elif args.skip_fm:
        print("\nGenerating random FM embeddings (--skip_fm)")
        rng2 = np.random.default_rng(0)
        X_fm = rng2.normal(0, 1, (len(records), 768)).astype(np.float32)
        X_fm /= np.linalg.norm(X_fm, axis=1, keepdims=True)
        np.save(fm_path, X_fm)
    else:
        print("\nComputing FM embeddings...")
        X_fm = compute_fm_embeddings(records,
                                     model_name=args.fm_model,
                                     use_llm=args.use_llm)
        np.save(fm_path, X_fm)
        print(f"  Saved → {fm_path}  shape={X_fm.shape}")
    _write_manifest(domains, len(records), n_per_level, want_fm_type)
    print(f"  Manifest updated: domains={sorted(domains)}, fm={want_fm_type}")

    # Verify FM variation within domain
    print("\nWithin-domain FM cosine similarity (should be < 0.95 for variation):")
    for d in list(set(task_arr))[:3]:
        mask = (task_arr == d)
        Xe   = X_fm[mask]
        cos  = float((Xe @ Xe.T).mean())
        print(f"  {d:<30} cos={cos:.4f}")

    # ── Save labels and task array ─────────────────────────────────────────
    np.save(DATA_DIR / "y_success.npy",  y_success)
    np.save(DATA_DIR / "y_nsteps.npy",   y_nsteps)
    np.save(DATA_DIR / "y_complex.npy",  y_complex)
    np.save(DATA_DIR / "task_types.npy", task_arr)

    # ── Meta splits (by domain, not instance) ─────────────────────────────
    unique_domains = list(np.unique(task_arr))
    test_domains_  = [d for d in TEST_DOMAINS  if d in unique_domains]
    val_domains_   = [d for d in VAL_DOMAINS   if d in unique_domains]
    train_domains_ = [d for d in unique_domains
                      if d not in test_domains_ and d not in val_domains_]

    def get_idx(doms):
        ts = set(doms)
        return [i for i, t in enumerate(task_arr) if t in ts]

    splits = {
        "meta_train": {"tasks": train_domains_, "indices": get_idx(train_domains_)},
        "meta_val":   {"tasks": val_domains_,   "indices": get_idx(val_domains_)},
        "meta_test":  {"tasks": test_domains_,  "indices": get_idx(test_domains_)},
    }

    registry = {
        "n_total":              len(records),
        "n_domains":            len(unique_domains),
        "surf_dim":             int(X_surf.shape[1]),
        "fm_dim":               int(X_fm.shape[1]),
        "fm_model":             args.fm_model if not args.skip_fm else "random",
        "use_llm_embeddings":   args.use_llm,
        "n_complexity_levels":  5,
        "domains":              unique_domains,
        "test_domains":         test_domains_,
        "val_domains":          val_domains_,
        "train_domains":        train_domains_,
        "splits": {k: {"tasks":       v["tasks"],
                       "n_instances": len(v["indices"])}
                   for k, v in splits.items()},
    }

    (DATA_DIR / "registry.json").write_text(json.dumps(registry, indent=2))
    for name, data in splits.items():
        np.save(DATA_DIR / f"idx_{name}.npy", np.array(data["indices"]))

    print(f"\nMeta-splits (by domain):")
    for name, data in splits.items():
        print(f"  {name:<12}: {len(data['tasks'])} domains, "
              f"{len(data['indices'])} instances")
        print(f"    Domains: {data['tasks']}")

    print(f"\nAll data saved to {DATA_DIR}/")
    print("Next: python plan_step2_rplm_baseline.py")


if __name__ == "__main__":
    main()